wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: huggingface
    huggingface_version: 4.4.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      2:
      - 1
      - 2
      - 3
      - 11
      4: 3.8.5
      5: 0.10.22
      6: 4.4.2
      8:
      - 5
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 1.0e-05
optimizer:
  desc: null
  value: adam
